### PR TITLE
Add support for socks proxy

### PR DESCRIPTION
**Pull request by LK4D4**
I'm trying to help with docker/docker#18373

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @nathanleclaire :smile:

**Comment by nathanleclaire** [comment]
Oh, nice!

**Comment by nathanleclaire** [comment]
What's the vendoring like for this repo?  I didn't notice any `vendor` or `Godeps` file and `golang.org/x/net/proxy` isn't in the standard library.

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
@nathanleclaire we're not doing vendoring for libraries

**Comment by calavera** [comment]
I just tagged the version `0.2.0` with this in. Feel free to vendor that tag with your PR.

**Comment by nathanleclaire** [comment]
:+1:

**Pull request merged**
