### PR TITLE
Support IPV6 addresses in ParsePortSpec

### PR DESCRIPTION
**Pull request by dnephin**
Replaces #17
Fixes docker/docker#11518

### CODE REVIEW

**Comment by lenovouser** [comment]
Friendly Ping? Also, https://github.com/docker/libnetwork/pull/1367 is necessary for this AFAIK.

**Comment by lenovouser** [comment]
Any progress?

**Comment by vdemeester** [comment]
LGTM 🐸
/cc @LK4D4 @mavenugo @thaJeztah

**Comment by phenomax** [comment]
What's the current state of development?
I'm looking forward to the support of ipv6 🔢

**Comment by lenovouser** [comment]
Hello? Anything happening?

**Pull request merged**
