### PR TITLE
Support parsing a single port spec

### PR DESCRIPTION
**Pull request by dnephin**
I extracted the port spec parsing into a function that supports an individual spec.

### CODE REVIEW

**Comment by dnephin** [comment]
Fixed the vet failures

**Comment by calavera** [comment]
can we have some tests for that function? otherwise LGTM

**Comment by dnephin** [comment]
This code is already pretty well covered by the old tests, but I added another one to test it directly.

**Comment by calavera** [comment]
awesome! :metal: LGTM

**Comment by thaJeztah** [comment]
looks like nat_test.go needs a gofmt

```
test -z "$(gofmt -s -l . | tee /dev/stderr)"
nat/nat_test.go

test -z "$(gofmt -s -l . | tee /dev/stderr)" returned exit code 1
```

**Comment by dnephin** [comment]
Fixed the gofmt

**Comment by icecrime** [comment]
LGTM

**Pull request merged**
