### PR TITLE
Vendor dependencies using LK4D4/vndr

### PR DESCRIPTION
**Pull request by thaJeztah**
This patch vendors the dependencies used by
go-connections, pinning them to a specific version.

Where possible, the same version/commit is used
as in moby/moby downstream.

ping @calavera @tiborvass @LK4D4 PTAL

### CODE REVIEW

**Comment by aaronlehmann** [comment]
This is purely a library package, so I don't think vendoring makes sense. The versions used here will always be superseded by versions vendored in the repo that builds an actual binary using this library. If something tries to use this library and doesn't vendor the dependencies itself, things will break, because types defined in the vendor dir won't match the types seen by the library user (this commonly happens with `Context`).

**Comment by thaJeztah** [comment]
Hm, so wondering; What's the usual approach to express; "This library package was tested / known to work with these versions of the dependencies"?

**Comment by aaronlehmann** [comment]
The go maintainers seem to disapprove of tying a library package to specific dependency versions. Typically, libraries are kept up-to-date to work with the master branches of any dependencies. So I don't know of a usual approach to this. All I can think of is noting this information in the README file.

**Comment by tiborvass** [comment]
Agree with @aaronlehmann. We could have a `vendor.conf` and a Dockerfile that has a `RUN vndr` layer. If `vendor.conf` only contains commits, then caching won't be a problem.

Also this is important only if we have CI. Seems like it's not set up properly.

**Comment by thaJeztah** [comment]
OK, let's close for now; the "just a `vendor.conf`" approach would work, but (as discussed with Tibor on Slack), without CI on this repo, there's no check whatsoever that everything is functional.

Thanks both!

**Pull request closed without merging**
