### PR TITLE
Update MAINTAINERS file with current maintainers

### PR DESCRIPTION
**Pull request by vdemeester**
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by vdemeester** [comment]
@dnephin agreed. I just wanted to update it with the team associated for now (so should be all ppl who have write permission on it). We can then discuss on who's interested to maintain 🙃 
😝

**Comment by thaJeztah** [comment]
Perhaps we can do the reverse, and ask who's interested?

**Comment by AkihiroSuda** [comment]
I'm interested in.

Also, can we consider bringing this back to moby/moby, as this library is almost solely used by Moby and Docker?

**Comment by thaJeztah** [comment]
> Also, can we consider bringing this back to moby/moby, as this library is almost solely used by Moby and Docker?

I'm not sure it's worth moving the code; there's a fairly low frequency of code changes, so it's not a big burden to maintain it separate I guess.

**Comment by vdemeester** [comment]
@dnephin @AkihiroSuda @thaJeztah Updated with the four of us then 😉

**Pull request merged**
